###########
# BUILDER #
###########

# Build pip requirements.
FROM python:3.9.7 AS build-reqs

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./api/requirements.txt requirements.txt
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

###########
# REACT BUILDER #
###########

# Use Node.js image to build React app
FROM node:18 AS react-build

WORKDIR /react-app
COPY ./client /react-app
RUN npm install && npm run build

#########
# FINAL #
#########

FROM python:3.9.7

RUN mkdir /app
WORKDIR /app

# create the appropriate directories
RUN mkdir /app/staticfiles

# install Python dependencies
COPY --from=build-reqs /app/wheels /wheels
COPY --from=build-reqs /app/requirements.txt requirements.txt
RUN pip install --no-cache /wheels/*

# install ODBC driver
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl gnupg2 && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18

# copy API files
COPY ./api .

# copy built React app to staticfiles folder
COPY --from=react-build /react-app/build /app/staticfiles

# expose the port
EXPOSE 80

CMD ["gunicorn", "-b", "0.0.0.0:80", "api:app"]
