###########
# BUILDER #
###########

# Build pip requirements.
FROM python:3.9.7-slim-buster as build-reqs

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./api/requirements.txt requirements.txt
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r requirements.txt

#########
# FINAL #
#########

FROM python:3.9.7-slim-buster

RUN mkdir /app
WORKDIR /app

# create the appropriate directories
RUN mkdir /app/staticfiles

# install dependencies
COPY --from=build-reqs /app/wheels /wheels
COPY --from=build-reqs /app/requirements.txt requirements.txt
RUN pip install --no-cache /wheels/*

# install ODBC driver
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl gnupg2 && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18

# copy api files
COPY ./api .

# copy the React app's build files into the container
COPY ../client/build /app/staticfiles

EXPOSE 80

CMD ["gunicorn", "-b", "0.0.0.0:80", "api:app"]
