upstream api {
    server api:8000;
    
}

server {

    listen 80 default_server;

    client_max_body_size 20M;

    location / {
        proxy_pass http://api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
    location /staticfiles/ {
        alias /app/staticfiles/;
    }

}


# server {
#     ##listen 443 ssl default_server;
#     ##server_name <sub_domain>.esurv.co.uk; # replace <sub_domain> with relevent domain e.g. prd-cmpt-01
#     ##ssl_certificate /etc/nginx/certs/<sub_domain>.crt; # see docs on how to generate https certificate
#     ##ssl_certificate_key /etc/nginx/certs/<sub_domain>.key;

#     client_max_body_size 20M;

#     location / {
#         proxy_pass http://api;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $host;
#         proxy_redirect off;
#     }

#     location /staticfiles/ {
#         alias /home/app/web/staticfiles/;
#     }
# }
